//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacadeService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FacadeService.IFacade")]
    public interface IFacade
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacade/GetData", ReplyAction="http://tempuri.org/IFacade/GetDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FacadeService.GetDataResponse> GetDataAsync(FacadeService.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacade/Initialize", ReplyAction="http://tempuri.org/IFacade/InitializeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FacadeService.InitializeResponse> InitializeAsync(FacadeService.InitializeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacade/UpdateResource", ReplyAction="http://tempuri.org/IFacade/UpdateResourceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FacadeService.UpdateResourceResponse> UpdateResourceAsync(FacadeService.UpdateResourceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacade/GetResources", ReplyAction="http://tempuri.org/IFacade/GetResourcesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FacadeService.GetResourcesResponse> GetResourcesAsync(FacadeService.GetResourcesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacade/NewResource", ReplyAction="http://tempuri.org/IFacade/NewResourceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FacadeService.NewResourceResponse> NewResourceAsync(FacadeService.NewResourceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacade/DeleteResource", ReplyAction="http://tempuri.org/IFacade/DeleteResourceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FacadeService.DeleteResourceResponse> DeleteResourceAsync(FacadeService.DeleteResourceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacade/UpdateAbility", ReplyAction="http://tempuri.org/IFacade/UpdateAbilityResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FacadeService.UpdateAbilityResponse> UpdateAbilityAsync(FacadeService.UpdateAbilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacade/GetAbilities", ReplyAction="http://tempuri.org/IFacade/GetAbilitiesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FacadeService.GetAbilitiesResponse> GetAbilitiesAsync(FacadeService.GetAbilitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacade/NewAbility", ReplyAction="http://tempuri.org/IFacade/NewAbilityResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FacadeService.NewAbilityResponse> NewAbilityAsync(FacadeService.NewAbilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacade/DeleteAbility", ReplyAction="http://tempuri.org/IFacade/DeleteAbilityResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FacadeService.DeleteAbilityResponse> DeleteAbilityAsync(FacadeService.DeleteAbilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacade/UpdateChampion", ReplyAction="http://tempuri.org/IFacade/UpdateChampionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FacadeService.UpdateChampionResponse> UpdateChampionAsync(FacadeService.UpdateChampionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacade/GetChampions", ReplyAction="http://tempuri.org/IFacade/GetChampionsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FacadeService.GetChampionsResponse> GetChampionsAsync(FacadeService.GetChampionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacade/NewChampion", ReplyAction="http://tempuri.org/IFacade/NewChampionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FacadeService.NewChampionResponse> NewChampionAsync(FacadeService.NewChampionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacade/DeleteChampion", ReplyAction="http://tempuri.org/IFacade/DeleteChampionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FacadeService.DeleteChampionResponse> DeleteChampionAsync(FacadeService.DeleteChampionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int value;
        
        public GetDataRequest()
        {
        }
        
        public GetDataRequest(int value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetDataResult;
        
        public GetDataResponse()
        {
        }
        
        public GetDataResponse(string GetDataResult)
        {
            this.GetDataResult = GetDataResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CCCTLibrary")]
    public partial class ReturnMessage
    {
        
        private ReturnMessage chainMessageField;
        
        private ReturnMessageDBScheme dBSchemeField;
        
        private ConnectionState dBStateField;
        
        private bool dBStateFieldSpecified;
        
        private Exception exceptionField;
        
        private string messageField;
        
        private bool wasSuccesfulField;
        
        private bool wasSuccesfulFieldSpecified;
        
        private string whereField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public ReturnMessage ChainMessage
        {
            get
            {
                return this.chainMessageField;
            }
            set
            {
                this.chainMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public ReturnMessageDBScheme DBScheme
        {
            get
            {
                return this.dBSchemeField;
            }
            set
            {
                this.dBSchemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ConnectionState DBState
        {
            get
            {
                return this.dBStateField;
            }
            set
            {
                this.dBStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DBStateSpecified
        {
            get
            {
                return this.dBStateFieldSpecified;
            }
            set
            {
                this.dBStateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public Exception Exception
        {
            get
            {
                return this.exceptionField;
            }
            set
            {
                this.exceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool WasSuccesful
        {
            get
            {
                return this.wasSuccesfulField;
            }
            set
            {
                this.wasSuccesfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WasSuccesfulSpecified
        {
            get
            {
                return this.wasSuccesfulFieldSpecified;
            }
            set
            {
                this.wasSuccesfulFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string Where
        {
            get
            {
                return this.whereField;
            }
            set
            {
                this.whereField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.datacontract.org/2004/07/CCCTLibrary")]
    public partial class ReturnMessageDBScheme
    {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private System.Xml.Linq.XElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.Linq.XElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class TupleOfArrayOfChampionReturnMessageaBdP6hTx
    {
        
        private Champion[] m_Item1Field;
        
        private ReturnMessage m_Item2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CCCTLibrary")]
        public Champion[] m_Item1
        {
            get
            {
                return this.m_Item1Field;
            }
            set
            {
                this.m_Item1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public ReturnMessage m_Item2
        {
            get
            {
                return this.m_Item2Field;
            }
            set
            {
                this.m_Item2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CCCTLibrary")]
    public partial class Champion
    {
        
        private string abilityPowerGrowthField;
        
        private string abilityPowerStartField;
        
        private string armorGrowthField;
        
        private string armorStartField;
        
        private string attackDamageGrowthField;
        
        private string attackDamageStartField;
        
        private string attackSpeedGrowthField;
        
        private string attackSpeedStartField;
        
        private string criticalStrikeChanceGrowthField;
        
        private string criticalStrikeChanceStartField;
        
        private Ability eAbilityField;
        
        private string healthGrowthField;
        
        private string healthRegenGrowthField;
        
        private string healthRegenStartField;
        
        private string healthStartField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string magicResistGrowthField;
        
        private string magicResistStartField;
        
        private string moveSpeedGrowthField;
        
        private string moveSpeedStartField;
        
        private string nameField;
        
        private Ability passiveAbilityField;
        
        private Ability qAbilityField;
        
        private Ability rAbilityField;
        
        private string rangeGrowthField;
        
        private string rangeStartField;
        
        private Resource resourceField;
        
        private string resourceGrowthField;
        
        private string resourceRegenGrowthField;
        
        private string resourceRegenStartField;
        
        private string resourceStartField;
        
        private Ability wAbilityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string AbilityPowerGrowth
        {
            get
            {
                return this.abilityPowerGrowthField;
            }
            set
            {
                this.abilityPowerGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string AbilityPowerStart
        {
            get
            {
                return this.abilityPowerStartField;
            }
            set
            {
                this.abilityPowerStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ArmorGrowth
        {
            get
            {
                return this.armorGrowthField;
            }
            set
            {
                this.armorGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string ArmorStart
        {
            get
            {
                return this.armorStartField;
            }
            set
            {
                this.armorStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string AttackDamageGrowth
        {
            get
            {
                return this.attackDamageGrowthField;
            }
            set
            {
                this.attackDamageGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string AttackDamageStart
        {
            get
            {
                return this.attackDamageStartField;
            }
            set
            {
                this.attackDamageStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string AttackSpeedGrowth
        {
            get
            {
                return this.attackSpeedGrowthField;
            }
            set
            {
                this.attackSpeedGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string AttackSpeedStart
        {
            get
            {
                return this.attackSpeedStartField;
            }
            set
            {
                this.attackSpeedStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string CriticalStrikeChanceGrowth
        {
            get
            {
                return this.criticalStrikeChanceGrowthField;
            }
            set
            {
                this.criticalStrikeChanceGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string CriticalStrikeChanceStart
        {
            get
            {
                return this.criticalStrikeChanceStartField;
            }
            set
            {
                this.criticalStrikeChanceStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public Ability EAbility
        {
            get
            {
                return this.eAbilityField;
            }
            set
            {
                this.eAbilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string HealthGrowth
        {
            get
            {
                return this.healthGrowthField;
            }
            set
            {
                this.healthGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string HealthRegenGrowth
        {
            get
            {
                return this.healthRegenGrowthField;
            }
            set
            {
                this.healthRegenGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string HealthRegenStart
        {
            get
            {
                return this.healthRegenStartField;
            }
            set
            {
                this.healthRegenStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string HealthStart
        {
            get
            {
                return this.healthStartField;
            }
            set
            {
                this.healthStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string MagicResistGrowth
        {
            get
            {
                return this.magicResistGrowthField;
            }
            set
            {
                this.magicResistGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string MagicResistStart
        {
            get
            {
                return this.magicResistStartField;
            }
            set
            {
                this.magicResistStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string MoveSpeedGrowth
        {
            get
            {
                return this.moveSpeedGrowthField;
            }
            set
            {
                this.moveSpeedGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string MoveSpeedStart
        {
            get
            {
                return this.moveSpeedStartField;
            }
            set
            {
                this.moveSpeedStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public Ability PassiveAbility
        {
            get
            {
                return this.passiveAbilityField;
            }
            set
            {
                this.passiveAbilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public Ability QAbility
        {
            get
            {
                return this.qAbilityField;
            }
            set
            {
                this.qAbilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public Ability RAbility
        {
            get
            {
                return this.rAbilityField;
            }
            set
            {
                this.rAbilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string RangeGrowth
        {
            get
            {
                return this.rangeGrowthField;
            }
            set
            {
                this.rangeGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string RangeStart
        {
            get
            {
                return this.rangeStartField;
            }
            set
            {
                this.rangeStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public Resource Resource
        {
            get
            {
                return this.resourceField;
            }
            set
            {
                this.resourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public string ResourceGrowth
        {
            get
            {
                return this.resourceGrowthField;
            }
            set
            {
                this.resourceGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public string ResourceRegenGrowth
        {
            get
            {
                return this.resourceRegenGrowthField;
            }
            set
            {
                this.resourceRegenGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public string ResourceRegenStart
        {
            get
            {
                return this.resourceRegenStartField;
            }
            set
            {
                this.resourceRegenStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public string ResourceStart
        {
            get
            {
                return this.resourceStartField;
            }
            set
            {
                this.resourceStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public Ability WAbility
        {
            get
            {
                return this.wAbilityField;
            }
            set
            {
                this.wAbilityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CCCTLibrary")]
    public partial class Ability
    {
        
        private string cooldownActField;
        
        private string cooldownEmpAltField;
        
        private string cooldownPasField;
        
        private string damageActField;
        
        private string damageEmpAltField;
        
        private string damagePasField;
        
        private string descriptionActField;
        
        private string descriptionEmpAltField;
        
        private string descriptionPasField;
        
        private bool haveActiveField;
        
        private bool haveActiveFieldSpecified;
        
        private bool haveEmpoweredOrAlternativeField;
        
        private bool haveEmpoweredOrAlternativeFieldSpecified;
        
        private bool havePassiveField;
        
        private bool havePassiveFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private bool isToogleAbleField;
        
        private bool isToogleAbleFieldSpecified;
        
        private string nameField;
        
        private string rangeActField;
        
        private string rangeEmpAltField;
        
        private string rangePasField;
        
        private string resourceCostActField;
        
        private string resourceCostEmpAltField;
        
        private Resource resourceUseField;
        
        private LibRepoAbilitySlot slotField;
        
        private bool slotFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string CooldownAct
        {
            get
            {
                return this.cooldownActField;
            }
            set
            {
                this.cooldownActField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string CooldownEmpAlt
        {
            get
            {
                return this.cooldownEmpAltField;
            }
            set
            {
                this.cooldownEmpAltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string CooldownPas
        {
            get
            {
                return this.cooldownPasField;
            }
            set
            {
                this.cooldownPasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string DamageAct
        {
            get
            {
                return this.damageActField;
            }
            set
            {
                this.damageActField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string DamageEmpAlt
        {
            get
            {
                return this.damageEmpAltField;
            }
            set
            {
                this.damageEmpAltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string DamagePas
        {
            get
            {
                return this.damagePasField;
            }
            set
            {
                this.damagePasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string DescriptionAct
        {
            get
            {
                return this.descriptionActField;
            }
            set
            {
                this.descriptionActField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string DescriptionEmpAlt
        {
            get
            {
                return this.descriptionEmpAltField;
            }
            set
            {
                this.descriptionEmpAltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string DescriptionPas
        {
            get
            {
                return this.descriptionPasField;
            }
            set
            {
                this.descriptionPasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool HaveActive
        {
            get
            {
                return this.haveActiveField;
            }
            set
            {
                this.haveActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HaveActiveSpecified
        {
            get
            {
                return this.haveActiveFieldSpecified;
            }
            set
            {
                this.haveActiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool HaveEmpoweredOrAlternative
        {
            get
            {
                return this.haveEmpoweredOrAlternativeField;
            }
            set
            {
                this.haveEmpoweredOrAlternativeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HaveEmpoweredOrAlternativeSpecified
        {
            get
            {
                return this.haveEmpoweredOrAlternativeFieldSpecified;
            }
            set
            {
                this.haveEmpoweredOrAlternativeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool HavePassive
        {
            get
            {
                return this.havePassiveField;
            }
            set
            {
                this.havePassiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HavePassiveSpecified
        {
            get
            {
                return this.havePassiveFieldSpecified;
            }
            set
            {
                this.havePassiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool IsToogleAble
        {
            get
            {
                return this.isToogleAbleField;
            }
            set
            {
                this.isToogleAbleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsToogleAbleSpecified
        {
            get
            {
                return this.isToogleAbleFieldSpecified;
            }
            set
            {
                this.isToogleAbleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string RangeAct
        {
            get
            {
                return this.rangeActField;
            }
            set
            {
                this.rangeActField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string RangeEmpAlt
        {
            get
            {
                return this.rangeEmpAltField;
            }
            set
            {
                this.rangeEmpAltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string RangePas
        {
            get
            {
                return this.rangePasField;
            }
            set
            {
                this.rangePasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string ResourceCostAct
        {
            get
            {
                return this.resourceCostActField;
            }
            set
            {
                this.resourceCostActField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string ResourceCostEmpAlt
        {
            get
            {
                return this.resourceCostEmpAltField;
            }
            set
            {
                this.resourceCostEmpAltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public Resource ResourceUse
        {
            get
            {
                return this.resourceUseField;
            }
            set
            {
                this.resourceUseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public LibRepoAbilitySlot Slot
        {
            get
            {
                return this.slotField;
            }
            set
            {
                this.slotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SlotSpecified
        {
            get
            {
                return this.slotFieldSpecified;
            }
            set
            {
                this.slotFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CCCTLibrary")]
    public partial class Resource
    {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int maxValueField;
        
        private bool maxValueFieldSpecified;
        
        private bool maxedAtStartField;
        
        private bool maxedAtStartFieldSpecified;
        
        private int minValueField;
        
        private bool minValueFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MaxValue
        {
            get
            {
                return this.maxValueField;
            }
            set
            {
                this.maxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxValueSpecified
        {
            get
            {
                return this.maxValueFieldSpecified;
            }
            set
            {
                this.maxValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool MaxedAtStart
        {
            get
            {
                return this.maxedAtStartField;
            }
            set
            {
                this.maxedAtStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxedAtStartSpecified
        {
            get
            {
                return this.maxedAtStartFieldSpecified;
            }
            set
            {
                this.maxedAtStartFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int MinValue
        {
            get
            {
                return this.minValueField;
            }
            set
            {
                this.minValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinValueSpecified
        {
            get
            {
                return this.minValueFieldSpecified;
            }
            set
            {
                this.minValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="LibRepo.AbilitySlot", Namespace="http://schemas.datacontract.org/2004/07/CCCTLibrary")]
    public enum LibRepoAbilitySlot
    {
        
        /// <remarks/>
        Passive,
        
        /// <remarks/>
        Q,
        
        /// <remarks/>
        W,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        R,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class TupleOfArrayOfAbilityReturnMessageaBdP6hTx
    {
        
        private Ability[] m_Item1Field;
        
        private ReturnMessage m_Item2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CCCTLibrary")]
        public Ability[] m_Item1
        {
            get
            {
                return this.m_Item1Field;
            }
            set
            {
                this.m_Item1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public ReturnMessage m_Item2
        {
            get
            {
                return this.m_Item2Field;
            }
            set
            {
                this.m_Item2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class TupleOfArrayOfResourceReturnMessageaBdP6hTx
    {
        
        private Resource[] m_Item1Field;
        
        private ReturnMessage m_Item2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CCCTLibrary")]
        public Resource[] m_Item1
        {
            get
            {
                return this.m_Item1Field;
            }
            set
            {
                this.m_Item1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public ReturnMessage m_Item2
        {
            get
            {
                return this.m_Item2Field;
            }
            set
            {
                this.m_Item2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class Exception
    {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private System.Xml.XmlQualifiedName factoryTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="", Order=0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        public System.Xml.XmlQualifiedName FactoryType
        {
            get
            {
                return this.factoryTypeField;
            }
            set
            {
                this.factoryTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    public enum ConnectionState
    {
        
        /// <remarks/>
        Closed = 1,
        
        /// <remarks/>
        Open = 2,
        
        /// <remarks/>
        Connecting = 4,
        
        /// <remarks/>
        Executing = 8,
        
        /// <remarks/>
        Fetching = 16,
        
        /// <remarks/>
        Broken = 32,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Initialize", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InitializeRequest
    {
        
        public InitializeRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitializeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InitializeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.ReturnMessage InitializeResult;
        
        public InitializeResponse()
        {
        }
        
        public InitializeResponse(FacadeService.ReturnMessage InitializeResult)
        {
            this.InitializeResult = InitializeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateResource", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateResourceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.Resource source;
        
        public UpdateResourceRequest()
        {
        }
        
        public UpdateResourceRequest(FacadeService.Resource source)
        {
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateResourceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateResourceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.ReturnMessage UpdateResourceResult;
        
        public UpdateResourceResponse()
        {
        }
        
        public UpdateResourceResponse(FacadeService.ReturnMessage UpdateResourceResult)
        {
            this.UpdateResourceResult = UpdateResourceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetResources", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetResourcesRequest
    {
        
        public GetResourcesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetResourcesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetResourcesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.TupleOfArrayOfResourceReturnMessageaBdP6hTx GetResourcesResult;
        
        public GetResourcesResponse()
        {
        }
        
        public GetResourcesResponse(FacadeService.TupleOfArrayOfResourceReturnMessageaBdP6hTx GetResourcesResult)
        {
            this.GetResourcesResult = GetResourcesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewResource", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewResourceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.Resource source;
        
        public NewResourceRequest()
        {
        }
        
        public NewResourceRequest(FacadeService.Resource source)
        {
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewResourceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewResourceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.ReturnMessage NewResourceResult;
        
        public NewResourceResponse()
        {
        }
        
        public NewResourceResponse(FacadeService.ReturnMessage NewResourceResult)
        {
            this.NewResourceResult = NewResourceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteResource", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteResourceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.Resource source;
        
        public DeleteResourceRequest()
        {
        }
        
        public DeleteResourceRequest(FacadeService.Resource source)
        {
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteResourceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteResourceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.ReturnMessage DeleteResourceResult;
        
        public DeleteResourceResponse()
        {
        }
        
        public DeleteResourceResponse(FacadeService.ReturnMessage DeleteResourceResult)
        {
            this.DeleteResourceResult = DeleteResourceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateAbility", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateAbilityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.Ability source;
        
        public UpdateAbilityRequest()
        {
        }
        
        public UpdateAbilityRequest(FacadeService.Ability source)
        {
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateAbilityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateAbilityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.ReturnMessage UpdateAbilityResult;
        
        public UpdateAbilityResponse()
        {
        }
        
        public UpdateAbilityResponse(FacadeService.ReturnMessage UpdateAbilityResult)
        {
            this.UpdateAbilityResult = UpdateAbilityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAbilities", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAbilitiesRequest
    {
        
        public GetAbilitiesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAbilitiesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAbilitiesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.TupleOfArrayOfAbilityReturnMessageaBdP6hTx GetAbilitiesResult;
        
        public GetAbilitiesResponse()
        {
        }
        
        public GetAbilitiesResponse(FacadeService.TupleOfArrayOfAbilityReturnMessageaBdP6hTx GetAbilitiesResult)
        {
            this.GetAbilitiesResult = GetAbilitiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewAbility", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewAbilityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.Ability source;
        
        public NewAbilityRequest()
        {
        }
        
        public NewAbilityRequest(FacadeService.Ability source)
        {
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewAbilityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewAbilityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.ReturnMessage NewAbilityResult;
        
        public NewAbilityResponse()
        {
        }
        
        public NewAbilityResponse(FacadeService.ReturnMessage NewAbilityResult)
        {
            this.NewAbilityResult = NewAbilityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteAbility", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteAbilityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.Ability source;
        
        public DeleteAbilityRequest()
        {
        }
        
        public DeleteAbilityRequest(FacadeService.Ability source)
        {
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteAbilityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteAbilityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.ReturnMessage DeleteAbilityResult;
        
        public DeleteAbilityResponse()
        {
        }
        
        public DeleteAbilityResponse(FacadeService.ReturnMessage DeleteAbilityResult)
        {
            this.DeleteAbilityResult = DeleteAbilityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateChampion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateChampionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.Champion source;
        
        public UpdateChampionRequest()
        {
        }
        
        public UpdateChampionRequest(FacadeService.Champion source)
        {
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateChampionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateChampionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.ReturnMessage UpdateChampionResult;
        
        public UpdateChampionResponse()
        {
        }
        
        public UpdateChampionResponse(FacadeService.ReturnMessage UpdateChampionResult)
        {
            this.UpdateChampionResult = UpdateChampionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetChampions", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetChampionsRequest
    {
        
        public GetChampionsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetChampionsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetChampionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.TupleOfArrayOfChampionReturnMessageaBdP6hTx GetChampionsResult;
        
        public GetChampionsResponse()
        {
        }
        
        public GetChampionsResponse(FacadeService.TupleOfArrayOfChampionReturnMessageaBdP6hTx GetChampionsResult)
        {
            this.GetChampionsResult = GetChampionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewChampion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewChampionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.Champion source;
        
        public NewChampionRequest()
        {
        }
        
        public NewChampionRequest(FacadeService.Champion source)
        {
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewChampionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewChampionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.ReturnMessage NewChampionResult;
        
        public NewChampionResponse()
        {
        }
        
        public NewChampionResponse(FacadeService.ReturnMessage NewChampionResult)
        {
            this.NewChampionResult = NewChampionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteChampion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteChampionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.Champion source;
        
        public DeleteChampionRequest()
        {
        }
        
        public DeleteChampionRequest(FacadeService.Champion source)
        {
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteChampionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteChampionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FacadeService.ReturnMessage DeleteChampionResult;
        
        public DeleteChampionResponse()
        {
        }
        
        public DeleteChampionResponse(FacadeService.ReturnMessage DeleteChampionResult)
        {
            this.DeleteChampionResult = DeleteChampionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IFacadeChannel : FacadeService.IFacade, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class FacadeClient : System.ServiceModel.ClientBase<FacadeService.IFacade>, FacadeService.IFacade
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FacadeClient() : 
                base(FacadeClient.GetDefaultBinding(), FacadeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IFacade.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FacadeClient(EndpointConfiguration endpointConfiguration) : 
                base(FacadeClient.GetBindingForEndpoint(endpointConfiguration), FacadeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FacadeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FacadeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FacadeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FacadeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<FacadeService.GetDataResponse> GetDataAsync(FacadeService.GetDataRequest request)
        {
            return base.Channel.GetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacadeService.InitializeResponse> InitializeAsync(FacadeService.InitializeRequest request)
        {
            return base.Channel.InitializeAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacadeService.UpdateResourceResponse> UpdateResourceAsync(FacadeService.UpdateResourceRequest request)
        {
            return base.Channel.UpdateResourceAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacadeService.GetResourcesResponse> GetResourcesAsync(FacadeService.GetResourcesRequest request)
        {
            return base.Channel.GetResourcesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacadeService.NewResourceResponse> NewResourceAsync(FacadeService.NewResourceRequest request)
        {
            return base.Channel.NewResourceAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacadeService.DeleteResourceResponse> DeleteResourceAsync(FacadeService.DeleteResourceRequest request)
        {
            return base.Channel.DeleteResourceAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacadeService.UpdateAbilityResponse> UpdateAbilityAsync(FacadeService.UpdateAbilityRequest request)
        {
            return base.Channel.UpdateAbilityAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacadeService.GetAbilitiesResponse> GetAbilitiesAsync(FacadeService.GetAbilitiesRequest request)
        {
            return base.Channel.GetAbilitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacadeService.NewAbilityResponse> NewAbilityAsync(FacadeService.NewAbilityRequest request)
        {
            return base.Channel.NewAbilityAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacadeService.DeleteAbilityResponse> DeleteAbilityAsync(FacadeService.DeleteAbilityRequest request)
        {
            return base.Channel.DeleteAbilityAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacadeService.UpdateChampionResponse> UpdateChampionAsync(FacadeService.UpdateChampionRequest request)
        {
            return base.Channel.UpdateChampionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacadeService.GetChampionsResponse> GetChampionsAsync(FacadeService.GetChampionsRequest request)
        {
            return base.Channel.GetChampionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacadeService.NewChampionResponse> NewChampionAsync(FacadeService.NewChampionRequest request)
        {
            return base.Channel.NewChampionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacadeService.DeleteChampionResponse> DeleteChampionAsync(FacadeService.DeleteChampionRequest request)
        {
            return base.Channel.DeleteChampionAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFacade))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFacade))
            {
                return new System.ServiceModel.EndpointAddress("http://www12.steenhoff.dk/Facade.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FacadeClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IFacade);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FacadeClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IFacade);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IFacade,
        }
    }
}
