--INSERT INTO [dbo].[Resources] ([Id], [Name], [MaxValue], [MinValue]) VALUES (0, 'Resourceless', 0, 0)
--INSERT INTO [dbo].[Resources] ([Id], [Name], [MaxValue], [MinValue]) VALUES (1, 'Mana', -1, 0)
