//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CCCTApp.FacadeService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IFacade", Namespace="http://tempuri.org/")]
    public partial class Facade : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitializeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateResourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetResourcesOperationCompleted;
        
        private System.Threading.SendOrPostCallback NewResourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteResourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateAbilityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAbilitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback NewAbilityOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteAbilityOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateChampionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChampionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback NewChampionOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteChampionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Facade() {
            this.Url = "http://www12.steenhoff.dk/Facade.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event InitializeCompletedEventHandler InitializeCompleted;
        
        /// <remarks/>
        public event UpdateResourceCompletedEventHandler UpdateResourceCompleted;
        
        /// <remarks/>
        public event GetResourcesCompletedEventHandler GetResourcesCompleted;
        
        /// <remarks/>
        public event NewResourceCompletedEventHandler NewResourceCompleted;
        
        /// <remarks/>
        public event DeleteResourceCompletedEventHandler DeleteResourceCompleted;
        
        /// <remarks/>
        public event UpdateAbilityCompletedEventHandler UpdateAbilityCompleted;
        
        /// <remarks/>
        public event GetAbilitiesCompletedEventHandler GetAbilitiesCompleted;
        
        /// <remarks/>
        public event NewAbilityCompletedEventHandler NewAbilityCompleted;
        
        /// <remarks/>
        public event DeleteAbilityCompletedEventHandler DeleteAbilityCompleted;
        
        /// <remarks/>
        public event UpdateChampionCompletedEventHandler UpdateChampionCompleted;
        
        /// <remarks/>
        public event GetChampionsCompletedEventHandler GetChampionsCompleted;
        
        /// <remarks/>
        public event NewChampionCompletedEventHandler NewChampionCompleted;
        
        /// <remarks/>
        public event DeleteChampionCompletedEventHandler DeleteChampionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFacade/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetData(int value, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valueSpecified) {
            object[] results = this.Invoke("GetData", new object[] {
                        value,
                        valueSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified) {
            this.GetDataAsync(value, valueSpecified, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        value,
                        valueSpecified}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFacade/Initialize", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReturnMessage Initialize() {
            object[] results = this.Invoke("Initialize", new object[0]);
            return ((ReturnMessage)(results[0]));
        }
        
        /// <remarks/>
        public void InitializeAsync() {
            this.InitializeAsync(null);
        }
        
        /// <remarks/>
        public void InitializeAsync(object userState) {
            if ((this.InitializeOperationCompleted == null)) {
                this.InitializeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializeOperationCompleted);
            }
            this.InvokeAsync("Initialize", new object[0], this.InitializeOperationCompleted, userState);
        }
        
        private void OnInitializeOperationCompleted(object arg) {
            if ((this.InitializeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializeCompleted(this, new InitializeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFacade/UpdateResource", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReturnMessage UpdateResource([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Resource source) {
            object[] results = this.Invoke("UpdateResource", new object[] {
                        source});
            return ((ReturnMessage)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateResourceAsync(Resource source) {
            this.UpdateResourceAsync(source, null);
        }
        
        /// <remarks/>
        public void UpdateResourceAsync(Resource source, object userState) {
            if ((this.UpdateResourceOperationCompleted == null)) {
                this.UpdateResourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateResourceOperationCompleted);
            }
            this.InvokeAsync("UpdateResource", new object[] {
                        source}, this.UpdateResourceOperationCompleted, userState);
        }
        
        private void OnUpdateResourceOperationCompleted(object arg) {
            if ((this.UpdateResourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateResourceCompleted(this, new UpdateResourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFacade/GetResources", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TupleOfArrayOfResourceReturnMessageaBdP6hTx GetResources() {
            object[] results = this.Invoke("GetResources", new object[0]);
            return ((TupleOfArrayOfResourceReturnMessageaBdP6hTx)(results[0]));
        }
        
        /// <remarks/>
        public void GetResourcesAsync() {
            this.GetResourcesAsync(null);
        }
        
        /// <remarks/>
        public void GetResourcesAsync(object userState) {
            if ((this.GetResourcesOperationCompleted == null)) {
                this.GetResourcesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResourcesOperationCompleted);
            }
            this.InvokeAsync("GetResources", new object[0], this.GetResourcesOperationCompleted, userState);
        }
        
        private void OnGetResourcesOperationCompleted(object arg) {
            if ((this.GetResourcesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResourcesCompleted(this, new GetResourcesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFacade/NewResource", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReturnMessage NewResource([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Resource source) {
            object[] results = this.Invoke("NewResource", new object[] {
                        source});
            return ((ReturnMessage)(results[0]));
        }
        
        /// <remarks/>
        public void NewResourceAsync(Resource source) {
            this.NewResourceAsync(source, null);
        }
        
        /// <remarks/>
        public void NewResourceAsync(Resource source, object userState) {
            if ((this.NewResourceOperationCompleted == null)) {
                this.NewResourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewResourceOperationCompleted);
            }
            this.InvokeAsync("NewResource", new object[] {
                        source}, this.NewResourceOperationCompleted, userState);
        }
        
        private void OnNewResourceOperationCompleted(object arg) {
            if ((this.NewResourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NewResourceCompleted(this, new NewResourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFacade/DeleteResource", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReturnMessage DeleteResource([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Resource source) {
            object[] results = this.Invoke("DeleteResource", new object[] {
                        source});
            return ((ReturnMessage)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteResourceAsync(Resource source) {
            this.DeleteResourceAsync(source, null);
        }
        
        /// <remarks/>
        public void DeleteResourceAsync(Resource source, object userState) {
            if ((this.DeleteResourceOperationCompleted == null)) {
                this.DeleteResourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteResourceOperationCompleted);
            }
            this.InvokeAsync("DeleteResource", new object[] {
                        source}, this.DeleteResourceOperationCompleted, userState);
        }
        
        private void OnDeleteResourceOperationCompleted(object arg) {
            if ((this.DeleteResourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteResourceCompleted(this, new DeleteResourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFacade/UpdateAbility", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReturnMessage UpdateAbility([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Ability source) {
            object[] results = this.Invoke("UpdateAbility", new object[] {
                        source});
            return ((ReturnMessage)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAbilityAsync(Ability source) {
            this.UpdateAbilityAsync(source, null);
        }
        
        /// <remarks/>
        public void UpdateAbilityAsync(Ability source, object userState) {
            if ((this.UpdateAbilityOperationCompleted == null)) {
                this.UpdateAbilityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAbilityOperationCompleted);
            }
            this.InvokeAsync("UpdateAbility", new object[] {
                        source}, this.UpdateAbilityOperationCompleted, userState);
        }
        
        private void OnUpdateAbilityOperationCompleted(object arg) {
            if ((this.UpdateAbilityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateAbilityCompleted(this, new UpdateAbilityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFacade/GetAbilities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TupleOfArrayOfAbilityReturnMessageaBdP6hTx GetAbilities() {
            object[] results = this.Invoke("GetAbilities", new object[0]);
            return ((TupleOfArrayOfAbilityReturnMessageaBdP6hTx)(results[0]));
        }
        
        /// <remarks/>
        public void GetAbilitiesAsync() {
            this.GetAbilitiesAsync(null);
        }
        
        /// <remarks/>
        public void GetAbilitiesAsync(object userState) {
            if ((this.GetAbilitiesOperationCompleted == null)) {
                this.GetAbilitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAbilitiesOperationCompleted);
            }
            this.InvokeAsync("GetAbilities", new object[0], this.GetAbilitiesOperationCompleted, userState);
        }
        
        private void OnGetAbilitiesOperationCompleted(object arg) {
            if ((this.GetAbilitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAbilitiesCompleted(this, new GetAbilitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFacade/NewAbility", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReturnMessage NewAbility([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Ability source) {
            object[] results = this.Invoke("NewAbility", new object[] {
                        source});
            return ((ReturnMessage)(results[0]));
        }
        
        /// <remarks/>
        public void NewAbilityAsync(Ability source) {
            this.NewAbilityAsync(source, null);
        }
        
        /// <remarks/>
        public void NewAbilityAsync(Ability source, object userState) {
            if ((this.NewAbilityOperationCompleted == null)) {
                this.NewAbilityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewAbilityOperationCompleted);
            }
            this.InvokeAsync("NewAbility", new object[] {
                        source}, this.NewAbilityOperationCompleted, userState);
        }
        
        private void OnNewAbilityOperationCompleted(object arg) {
            if ((this.NewAbilityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NewAbilityCompleted(this, new NewAbilityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFacade/DeleteAbility", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReturnMessage DeleteAbility([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Ability source) {
            object[] results = this.Invoke("DeleteAbility", new object[] {
                        source});
            return ((ReturnMessage)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAbilityAsync(Ability source) {
            this.DeleteAbilityAsync(source, null);
        }
        
        /// <remarks/>
        public void DeleteAbilityAsync(Ability source, object userState) {
            if ((this.DeleteAbilityOperationCompleted == null)) {
                this.DeleteAbilityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAbilityOperationCompleted);
            }
            this.InvokeAsync("DeleteAbility", new object[] {
                        source}, this.DeleteAbilityOperationCompleted, userState);
        }
        
        private void OnDeleteAbilityOperationCompleted(object arg) {
            if ((this.DeleteAbilityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteAbilityCompleted(this, new DeleteAbilityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFacade/UpdateChampion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReturnMessage UpdateChampion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Champion source) {
            object[] results = this.Invoke("UpdateChampion", new object[] {
                        source});
            return ((ReturnMessage)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateChampionAsync(Champion source) {
            this.UpdateChampionAsync(source, null);
        }
        
        /// <remarks/>
        public void UpdateChampionAsync(Champion source, object userState) {
            if ((this.UpdateChampionOperationCompleted == null)) {
                this.UpdateChampionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateChampionOperationCompleted);
            }
            this.InvokeAsync("UpdateChampion", new object[] {
                        source}, this.UpdateChampionOperationCompleted, userState);
        }
        
        private void OnUpdateChampionOperationCompleted(object arg) {
            if ((this.UpdateChampionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateChampionCompleted(this, new UpdateChampionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFacade/GetChampions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TupleOfArrayOfChampionReturnMessageaBdP6hTx GetChampions() {
            object[] results = this.Invoke("GetChampions", new object[0]);
            return ((TupleOfArrayOfChampionReturnMessageaBdP6hTx)(results[0]));
        }
        
        /// <remarks/>
        public void GetChampionsAsync() {
            this.GetChampionsAsync(null);
        }
        
        /// <remarks/>
        public void GetChampionsAsync(object userState) {
            if ((this.GetChampionsOperationCompleted == null)) {
                this.GetChampionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChampionsOperationCompleted);
            }
            this.InvokeAsync("GetChampions", new object[0], this.GetChampionsOperationCompleted, userState);
        }
        
        private void OnGetChampionsOperationCompleted(object arg) {
            if ((this.GetChampionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChampionsCompleted(this, new GetChampionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFacade/NewChampion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReturnMessage NewChampion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Champion source) {
            object[] results = this.Invoke("NewChampion", new object[] {
                        source});
            return ((ReturnMessage)(results[0]));
        }
        
        /// <remarks/>
        public void NewChampionAsync(Champion source) {
            this.NewChampionAsync(source, null);
        }
        
        /// <remarks/>
        public void NewChampionAsync(Champion source, object userState) {
            if ((this.NewChampionOperationCompleted == null)) {
                this.NewChampionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewChampionOperationCompleted);
            }
            this.InvokeAsync("NewChampion", new object[] {
                        source}, this.NewChampionOperationCompleted, userState);
        }
        
        private void OnNewChampionOperationCompleted(object arg) {
            if ((this.NewChampionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NewChampionCompleted(this, new NewChampionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFacade/DeleteChampion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReturnMessage DeleteChampion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Champion source) {
            object[] results = this.Invoke("DeleteChampion", new object[] {
                        source});
            return ((ReturnMessage)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteChampionAsync(Champion source) {
            this.DeleteChampionAsync(source, null);
        }
        
        /// <remarks/>
        public void DeleteChampionAsync(Champion source, object userState) {
            if ((this.DeleteChampionOperationCompleted == null)) {
                this.DeleteChampionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteChampionOperationCompleted);
            }
            this.InvokeAsync("DeleteChampion", new object[] {
                        source}, this.DeleteChampionOperationCompleted, userState);
        }
        
        private void OnDeleteChampionOperationCompleted(object arg) {
            if ((this.DeleteChampionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteChampionCompleted(this, new DeleteChampionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CCCTLibrary")]
    public partial class ReturnMessage {
        
        private ReturnMessage chainMessageField;
        
        private System.Data.DataTable dBSchemeField;
        
        private ConnectionState dBStateField;
        
        private bool dBStateFieldSpecified;
        
        private Exception exceptionField;
        
        private string messageField;
        
        private bool wasSuccesfulField;
        
        private bool wasSuccesfulFieldSpecified;
        
        private string whereField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReturnMessage ChainMessage {
            get {
                return this.chainMessageField;
            }
            set {
                this.chainMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable DBScheme {
            get {
                return this.dBSchemeField;
            }
            set {
                this.dBSchemeField = value;
            }
        }
        
        /// <remarks/>
        public ConnectionState DBState {
            get {
                return this.dBStateField;
            }
            set {
                this.dBStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DBStateSpecified {
            get {
                return this.dBStateFieldSpecified;
            }
            set {
                this.dBStateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Exception Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool WasSuccesful {
            get {
                return this.wasSuccesfulField;
            }
            set {
                this.wasSuccesfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WasSuccesfulSpecified {
            get {
                return this.wasSuccesfulFieldSpecified;
            }
            set {
                this.wasSuccesfulFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Where {
            get {
                return this.whereField;
            }
            set {
                this.whereField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    public enum ConnectionState {
        
        /// <remarks/>
        Closed = 1,
        
        /// <remarks/>
        Open = 2,
        
        /// <remarks/>
        Connecting = 4,
        
        /// <remarks/>
        Executing = 8,
        
        /// <remarks/>
        Fetching = 16,
        
        /// <remarks/>
        Broken = 32,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class Exception {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlQualifiedName factoryTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        public System.Xml.XmlQualifiedName FactoryType {
            get {
                return this.factoryTypeField;
            }
            set {
                this.factoryTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class TupleOfArrayOfChampionReturnMessageaBdP6hTx {
        
        private Champion[] m_Item1Field;
        
        private ReturnMessage m_Item2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CCCTLibrary")]
        public Champion[] m_Item1 {
            get {
                return this.m_Item1Field;
            }
            set {
                this.m_Item1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReturnMessage m_Item2 {
            get {
                return this.m_Item2Field;
            }
            set {
                this.m_Item2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CCCTLibrary")]
    public partial class Champion {
        
        private string abilityPowerGrowthField;
        
        private string abilityPowerStartField;
        
        private string armorGrowthField;
        
        private string armorStartField;
        
        private string attackDamageGrowthField;
        
        private string attackDamageStartField;
        
        private string attackSpeedGrowthField;
        
        private string attackSpeedStartField;
        
        private string criticalStrikeChanceGrowthField;
        
        private string criticalStrikeChanceStartField;
        
        private Ability eAbilityField;
        
        private string healthGrowthField;
        
        private string healthRegenGrowthField;
        
        private string healthRegenStartField;
        
        private string healthStartField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string magicResistGrowthField;
        
        private string magicResistStartField;
        
        private string moveSpeedGrowthField;
        
        private string moveSpeedStartField;
        
        private string nameField;
        
        private Ability passiveAbilityField;
        
        private Ability qAbilityField;
        
        private Ability rAbilityField;
        
        private string rangeGrowthField;
        
        private string rangeStartField;
        
        private Resource resourceField;
        
        private string resourceGrowthField;
        
        private string resourceRegenGrowthField;
        
        private string resourceRegenStartField;
        
        private string resourceStartField;
        
        private Ability wAbilityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AbilityPowerGrowth {
            get {
                return this.abilityPowerGrowthField;
            }
            set {
                this.abilityPowerGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AbilityPowerStart {
            get {
                return this.abilityPowerStartField;
            }
            set {
                this.abilityPowerStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ArmorGrowth {
            get {
                return this.armorGrowthField;
            }
            set {
                this.armorGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ArmorStart {
            get {
                return this.armorStartField;
            }
            set {
                this.armorStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AttackDamageGrowth {
            get {
                return this.attackDamageGrowthField;
            }
            set {
                this.attackDamageGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AttackDamageStart {
            get {
                return this.attackDamageStartField;
            }
            set {
                this.attackDamageStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AttackSpeedGrowth {
            get {
                return this.attackSpeedGrowthField;
            }
            set {
                this.attackSpeedGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AttackSpeedStart {
            get {
                return this.attackSpeedStartField;
            }
            set {
                this.attackSpeedStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CriticalStrikeChanceGrowth {
            get {
                return this.criticalStrikeChanceGrowthField;
            }
            set {
                this.criticalStrikeChanceGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CriticalStrikeChanceStart {
            get {
                return this.criticalStrikeChanceStartField;
            }
            set {
                this.criticalStrikeChanceStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ability EAbility {
            get {
                return this.eAbilityField;
            }
            set {
                this.eAbilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HealthGrowth {
            get {
                return this.healthGrowthField;
            }
            set {
                this.healthGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HealthRegenGrowth {
            get {
                return this.healthRegenGrowthField;
            }
            set {
                this.healthRegenGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HealthRegenStart {
            get {
                return this.healthRegenStartField;
            }
            set {
                this.healthRegenStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HealthStart {
            get {
                return this.healthStartField;
            }
            set {
                this.healthStartField = value;
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MagicResistGrowth {
            get {
                return this.magicResistGrowthField;
            }
            set {
                this.magicResistGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MagicResistStart {
            get {
                return this.magicResistStartField;
            }
            set {
                this.magicResistStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MoveSpeedGrowth {
            get {
                return this.moveSpeedGrowthField;
            }
            set {
                this.moveSpeedGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MoveSpeedStart {
            get {
                return this.moveSpeedStartField;
            }
            set {
                this.moveSpeedStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ability PassiveAbility {
            get {
                return this.passiveAbilityField;
            }
            set {
                this.passiveAbilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ability QAbility {
            get {
                return this.qAbilityField;
            }
            set {
                this.qAbilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ability RAbility {
            get {
                return this.rAbilityField;
            }
            set {
                this.rAbilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RangeGrowth {
            get {
                return this.rangeGrowthField;
            }
            set {
                this.rangeGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RangeStart {
            get {
                return this.rangeStartField;
            }
            set {
                this.rangeStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Resource Resource {
            get {
                return this.resourceField;
            }
            set {
                this.resourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ResourceGrowth {
            get {
                return this.resourceGrowthField;
            }
            set {
                this.resourceGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ResourceRegenGrowth {
            get {
                return this.resourceRegenGrowthField;
            }
            set {
                this.resourceRegenGrowthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ResourceRegenStart {
            get {
                return this.resourceRegenStartField;
            }
            set {
                this.resourceRegenStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ResourceStart {
            get {
                return this.resourceStartField;
            }
            set {
                this.resourceStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ability WAbility {
            get {
                return this.wAbilityField;
            }
            set {
                this.wAbilityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CCCTLibrary")]
    public partial class Ability {
        
        private string cooldownActField;
        
        private string cooldownEmpAltField;
        
        private string cooldownPasField;
        
        private string damageActField;
        
        private string damageEmpAltField;
        
        private string damagePasField;
        
        private string descriptionActField;
        
        private string descriptionEmpAltField;
        
        private string descriptionPasField;
        
        private bool haveActiveField;
        
        private bool haveActiveFieldSpecified;
        
        private bool haveEmpoweredOrAlternativeField;
        
        private bool haveEmpoweredOrAlternativeFieldSpecified;
        
        private bool havePassiveField;
        
        private bool havePassiveFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private bool isToogleAbleField;
        
        private bool isToogleAbleFieldSpecified;
        
        private string nameField;
        
        private string rangeActField;
        
        private string rangeEmpAltField;
        
        private string rangePasField;
        
        private string resourceCostActField;
        
        private string resourceCostEmpAltField;
        
        private Resource resourceUseField;
        
        private LibRepoAbilitySlot slotField;
        
        private bool slotFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CooldownAct {
            get {
                return this.cooldownActField;
            }
            set {
                this.cooldownActField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CooldownEmpAlt {
            get {
                return this.cooldownEmpAltField;
            }
            set {
                this.cooldownEmpAltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CooldownPas {
            get {
                return this.cooldownPasField;
            }
            set {
                this.cooldownPasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DamageAct {
            get {
                return this.damageActField;
            }
            set {
                this.damageActField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DamageEmpAlt {
            get {
                return this.damageEmpAltField;
            }
            set {
                this.damageEmpAltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DamagePas {
            get {
                return this.damagePasField;
            }
            set {
                this.damagePasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DescriptionAct {
            get {
                return this.descriptionActField;
            }
            set {
                this.descriptionActField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DescriptionEmpAlt {
            get {
                return this.descriptionEmpAltField;
            }
            set {
                this.descriptionEmpAltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DescriptionPas {
            get {
                return this.descriptionPasField;
            }
            set {
                this.descriptionPasField = value;
            }
        }
        
        /// <remarks/>
        public bool HaveActive {
            get {
                return this.haveActiveField;
            }
            set {
                this.haveActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HaveActiveSpecified {
            get {
                return this.haveActiveFieldSpecified;
            }
            set {
                this.haveActiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool HaveEmpoweredOrAlternative {
            get {
                return this.haveEmpoweredOrAlternativeField;
            }
            set {
                this.haveEmpoweredOrAlternativeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HaveEmpoweredOrAlternativeSpecified {
            get {
                return this.haveEmpoweredOrAlternativeFieldSpecified;
            }
            set {
                this.haveEmpoweredOrAlternativeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool HavePassive {
            get {
                return this.havePassiveField;
            }
            set {
                this.havePassiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HavePassiveSpecified {
            get {
                return this.havePassiveFieldSpecified;
            }
            set {
                this.havePassiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsToogleAble {
            get {
                return this.isToogleAbleField;
            }
            set {
                this.isToogleAbleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsToogleAbleSpecified {
            get {
                return this.isToogleAbleFieldSpecified;
            }
            set {
                this.isToogleAbleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RangeAct {
            get {
                return this.rangeActField;
            }
            set {
                this.rangeActField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RangeEmpAlt {
            get {
                return this.rangeEmpAltField;
            }
            set {
                this.rangeEmpAltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RangePas {
            get {
                return this.rangePasField;
            }
            set {
                this.rangePasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ResourceCostAct {
            get {
                return this.resourceCostActField;
            }
            set {
                this.resourceCostActField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ResourceCostEmpAlt {
            get {
                return this.resourceCostEmpAltField;
            }
            set {
                this.resourceCostEmpAltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Resource ResourceUse {
            get {
                return this.resourceUseField;
            }
            set {
                this.resourceUseField = value;
            }
        }
        
        /// <remarks/>
        public LibRepoAbilitySlot Slot {
            get {
                return this.slotField;
            }
            set {
                this.slotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SlotSpecified {
            get {
                return this.slotFieldSpecified;
            }
            set {
                this.slotFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CCCTLibrary")]
    public partial class Resource {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int maxValueField;
        
        private bool maxValueFieldSpecified;
        
        private bool maxedAtStartField;
        
        private bool maxedAtStartFieldSpecified;
        
        private int minValueField;
        
        private bool minValueFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int MaxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxValueSpecified {
            get {
                return this.maxValueFieldSpecified;
            }
            set {
                this.maxValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool MaxedAtStart {
            get {
                return this.maxedAtStartField;
            }
            set {
                this.maxedAtStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxedAtStartSpecified {
            get {
                return this.maxedAtStartFieldSpecified;
            }
            set {
                this.maxedAtStartFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int MinValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinValueSpecified {
            get {
                return this.minValueFieldSpecified;
            }
            set {
                this.minValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="LibRepo.AbilitySlot", Namespace="http://schemas.datacontract.org/2004/07/CCCTLibrary")]
    public enum LibRepoAbilitySlot {
        
        /// <remarks/>
        Passive,
        
        /// <remarks/>
        Q,
        
        /// <remarks/>
        W,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        R,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class TupleOfArrayOfAbilityReturnMessageaBdP6hTx {
        
        private Ability[] m_Item1Field;
        
        private ReturnMessage m_Item2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CCCTLibrary")]
        public Ability[] m_Item1 {
            get {
                return this.m_Item1Field;
            }
            set {
                this.m_Item1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReturnMessage m_Item2 {
            get {
                return this.m_Item2Field;
            }
            set {
                this.m_Item2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class TupleOfArrayOfResourceReturnMessageaBdP6hTx {
        
        private Resource[] m_Item1Field;
        
        private ReturnMessage m_Item2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CCCTLibrary")]
        public Resource[] m_Item1 {
            get {
                return this.m_Item1Field;
            }
            set {
                this.m_Item1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReturnMessage m_Item2 {
            get {
                return this.m_Item2Field;
            }
            set {
                this.m_Item2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void InitializeCompletedEventHandler(object sender, InitializeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InitializeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InitializeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateResourceCompletedEventHandler(object sender, UpdateResourceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateResourceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateResourceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetResourcesCompletedEventHandler(object sender, GetResourcesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResourcesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResourcesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TupleOfArrayOfResourceReturnMessageaBdP6hTx Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TupleOfArrayOfResourceReturnMessageaBdP6hTx)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void NewResourceCompletedEventHandler(object sender, NewResourceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewResourceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NewResourceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DeleteResourceCompletedEventHandler(object sender, DeleteResourceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteResourceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteResourceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateAbilityCompletedEventHandler(object sender, UpdateAbilityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateAbilityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateAbilityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAbilitiesCompletedEventHandler(object sender, GetAbilitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAbilitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAbilitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TupleOfArrayOfAbilityReturnMessageaBdP6hTx Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TupleOfArrayOfAbilityReturnMessageaBdP6hTx)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void NewAbilityCompletedEventHandler(object sender, NewAbilityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewAbilityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NewAbilityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DeleteAbilityCompletedEventHandler(object sender, DeleteAbilityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteAbilityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteAbilityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateChampionCompletedEventHandler(object sender, UpdateChampionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateChampionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateChampionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetChampionsCompletedEventHandler(object sender, GetChampionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChampionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChampionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TupleOfArrayOfChampionReturnMessageaBdP6hTx Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TupleOfArrayOfChampionReturnMessageaBdP6hTx)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void NewChampionCompletedEventHandler(object sender, NewChampionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewChampionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NewChampionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DeleteChampionCompletedEventHandler(object sender, DeleteChampionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteChampionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteChampionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMessage)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591